### ISSUE TITLE
External helpers

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#105]
So I am in the need of having a external file for helpers. @wesleycho created a `hasClass` which is useful for example on `rating` where I am using `classList` (which is not IE9 compatible).

The thing is... how?

If I create it for example in `misc/test-lib/functions.ts` I have to do in `rating.spec.ts`:

```typescript
import {hasClass} from '../../misc/test-lib/functions
```

IDE agrees on that, but after it gets transpiled into `.js`, it is not going to work anymore (the CJS will try to require a .ts file).

So... transpile it? At first I thought about transpiling all of that into `temp/`, but the problem is that the paths will change from the original `spec.ts` file and the one that gets into `temp`.

So if I have to do:

```typescript
import {hasClass} from '../../misc/test-lib/functions
```

In the `temp` folder I would need to require it from `../../functions.js` or `../../test-lib/functions.js`. In both options, path changes from original to transpiled.

I could leave helpers in plain javascript and tune karma to pick them. By coincidence, the path won't change in this case, because both original test files and transpiled one are two folder deep so it will always be `../../misc/test-lib/functions.js` ...

Problem with that is that typescript is gonna need definition files or perhaps simply complain...

What to do... What to do... Thoughts?

**Comment by Foxandxss** [comment]
Yet another task / watch for helpers that will transpile it in the same exact folder could work, but is that pretty?

**Comment by wesleycho** [comment]
IMO it is better to just do the `../../` - by changing the file path, it adds confusion & isn't as clear what is going on.

**Comment by pkozlowski-opensource** [comment]
We've got https://github.com/ng-bootstrap/core/blob/master/src/util/util.ts for now so let's stick helpers in there for now. Will see how things evolve.
