### ISSUE TITLE
Cannot use collapse as var

### ISSUE THREAD

**Issue by sirajc** [ng-bootstrap/core#112]
When we create *var* for collapse like `<div ngb-collapse #myCollapse>` and try to accesss values like {{myCollapse.collapsed}}, then it gives error `Cannot access collapsed of undefined`

**Comment by sirajc** [comment]
As per a3ce4e3d5a05d7aac1de6b01998d59d383a953f4 , @pkozlowski-opensource has used `export='ngbDropdown'`. Do we have to add this for ngb-Collapse as well, thoughts?
Don't angular2 directly create vars when referenced with # on its own?

**Comment by Foxandxss** [comment]
Depends on what your team does with collapse. I had planned this exportAs
thing for the next meeting.

**Comment by sirajc** [comment]
ok, is there any other channels for discussion like slack?

**Comment by Foxandxss** [comment]
There is a ng2 channel in angularbuddies slack. This team has a channel
there, but it is private sorry

**Comment by Foxandxss** [comment]
And you were right (not that I am at home). I thought that you could get the element ref when you wanted to and not only if you export it. I think that is new... uhm...

**Comment by pkozlowski-opensource** [comment]
@sirajc HTML is not case-sensitive nor case-preserving so you can't do `<div ngb-collapse #myCollapse>`, try `<div ngb-collapse #mycollapse>` instead. But this still won't work as NgbCollapse is not exporting itself right now.

You are raising an interesting question thought - how people should be toggling collapse? If we re-export it people will have 2 methods:

```html
<button (click)="isOpen = !isOpen">Toggle open</button>
<div ngb-collapse="isOpen">...</div>
```

or:

```html
<button (click)="mycollapse.open = !mycollapse.open">Toggle open</button>
<div ngb-collapse #mycollapse="ngbCollapse">...</div>
```

I'm not sure I can think of anything _bad_ with supporting 2 patterns, but we are advancing into new territory so I'm sure that different patters / best practices will emerge here.

**Comment by sirajc** [comment]
Thanks for details. will wait for design to mature and team's decisions.
In case if we go with second option and introduce export, then we can provide a toggle function, which will be a nice sugar on the API, some thing like
```
<button (click)="mycollapse.toggle()">Toggle</button>
<div ngb-collapse #mycollapse="ngbCollapse">...</div>
```

**Comment by sirajc** [comment]
This is fixed by 1001e3cb63c086b68523e9c7eb85611a7ab620b5 
Any thoughts on toggle Api, mentioned in above comment

**Comment by pkozlowski-opensource** [comment]
Yes, imo it would be good to have public methods like open, close and toggle

**Comment by Foxandxss** [comment]
That is basically sugar yes, but I am not really sure. This `exportAs` thing opens a door to new sugar, but I need think more about that.

**Comment by wesleycho** [comment]
I should add that ng2 changed syntax since this discussion started, so now one has to do `<div ngbCollapse #myCollapse="ngbCollapse">` I believe
