### ISSUE TITLE
Pagination: max number of pages and ellipsis support 

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#116]
We should support 2 additional options:
- max number of pages displayed 
- ellipsis if max no of displayed pages is exceeded

**Comment by wesleycho** [comment]
By ellipsis, do you mean like given a max page of 100, and we are displaying 5 at a time, the UI would be like this?

<< ... 31 32 33 34 35 ... >>

**Comment by pkozlowski-opensource** [comment]
> By ellipsis, do you mean

Actually I don't know what I've meant by this :-) Meant to check what exists in the current version of the library + check opened / closed issues to check what we've rejected (or not)

Feel free to take over this one if you remember / know those patterns

**Comment by pkozlowski-opensource** [comment]
Closing in favor of more-specific issues I've just opened.
