### ISSUE TITLE
Missing progressbar features

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#118]
It is missing (will update this if I get more in mind):

- [ ] Animation
- [x] Calculation corner cases
- [x] Aria support.
- [ ] Multi bars (if supported).

**Comment by pkozlowski-opensource** [comment]
What do you mean by "Multi bars"? Stacked ones? I can't see them any more in BS4 (maybe since it is still in alpha).

Man, we are building on alphas all the way down...

**Comment by Foxandxss** [comment]
Yeah. Clarified that.

And this is bleeding bleeding bleeding edge.

**Comment by pkozlowski-opensource** [comment]
I think that the only missing thing is the `animated` flag so I've opened a more focused issue: #285
