### ISSUE TITLE
Affix

### ISSUE THREAD

**Issue by BobbieBarker** [ng-bootstrap/core#13]
Recreate BS3 Affix with ng2 component.

**Comment by pkozlowski-opensource** [comment]
Seems like bs4 is dropping affix. From http://v4-alpha.getbootstrap.com/migration/: 

> Dropped the Affix jQuery plugin. We recommend using a position: sticky polyfill instead. 
If you were using Affix to apply additional, non-position styles, the polyfills might not support your use case. One option for such uses is the third-party ScrollPos-Styler library.

As such I don't think we should rush to add this one. Closing an issue for now, we can always revisit it later.
