### ISSUE TITLE
Convention: aria tests

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#130]
Call me a romantic, but I had an idea (I put in practice in `rating`).

I decided to put all my aria related tests in a concrete describe instead of mixing it with other tests.

That way we can see easily everything we done regarding aria in one place. Imo it is better than having to read test by test to see if we do some aria assertion in there.

So what do you think? You like my idea of a big describe (inside `UI logic`) for all aria related tests and leave the other tests without touching aria or just test the aria stuff when it makes sense in the other tests.

AKA rating tests vs collapse tests.

**Comment by icfantv** [comment]
That sounds good.

**Comment by wesleycho** [comment]
I'm fine with that - should not really interfere with any other test organization we might do.

**Comment by pkozlowski-opensource** [comment]
I'm 50/50. Usually aria attributes should follow some changes in markup (ex.: you collapse sth so need to check both that collapsed part is hidden _and_ that proper aria flags are set). I'm afraid that this proposal will lead to code duplication in tests (all the scenarios will have to be duplicated).

Yeh, thinking about some more it is a timid -1 from me. Open to convincing arguments, though. Maybe @Foxandxss could refactor tests for one of the directives and compare the impact? This way we would have solid data and could take proper decision.

**Comment by Foxandxss** [comment]
@pkozlowski-opensource check rating tests.

**Comment by pkozlowski-opensource** [comment]
Right. So yeh, looking at rating tests confirms my initial thinking that it might lead to code duplication. Just compare:

```javascript
it('initializes the default star icons as selected', injectAsync([TestComponentBuilder], (tcb) => {
       const html = '<ngb-rating rate="3" max="5"></ngb-rating>';

       return tcb.overrideTemplate(TestComponent, html).createAsync(TestComponent).then((fixture) => {
         fixture.detectChanges();

         const compiled = fixture.nativeElement;

         expect(getState(compiled)).toEqual([true, true, true, false, false]);
       });
     }));
```

and 

```javascript
it('initializes populates the current rate for screenreaders', injectAsync([TestComponentBuilder], (tcb) => {
         const html = '<ngb-rating rate="3" max="5"></ngb-rating>';

         return tcb.overrideTemplate(TestComponent, html).createAsync(TestComponent).then((fixture) => {
           fixture.detectChanges();

           const compiled = fixture.nativeElement;

           expect(getAriaState(compiled)).toEqual([true, true, true, false, false]);
         });
       }));
```

**Comment by pkozlowski-opensource** [comment]
It is essentially the same test, there is just one line difference in assertion. Yeh, this is solid -1 from me now. Still happy to be convinced otherwise :-)
