### ISSUE TITLE
[tooltip] exploring various API options

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#145]
I would like to kick-off the discussion on the various API styles we can offer for tooltip / popover / modal users. We need to put a bit of thinking into it a with Angular2 one can't simply say "here is a URL of a template, load me this here". We've got view boundaries and the only things we can insert are:
* templates (things wrapped in the `template` tag)
* components

Actually the same limitations apply to the Angular 2 router.

Now, as of today I can think of the 3 different styles of API (at this point I'm not even sure if all of them are implementable):

### Named TemplateRef 

```html
<template #foo>
    Some <b>fancy</b> content
</template>
<div [ngb-tooltip]="foo">
```

### Embedded TemplateRef 

```html
<div [ngb-tooltip]="foo">
    <template #foo>
        Some <b>fancy</b> content
    </template>
</div>
```

### ComponentRef 
Assuming that `Foo` is a component:
```html
<div [ngb-tooltip]="Foo">
```

**Comment by pkozlowski-opensource** [comment]
From my very brief checks _none_ of the above proposals is (easily) implementable at the moment, so we will have to work closely with the Angular2 team to properly cover this use-case.

**Comment by pkozlowski-opensource** [comment]
"Named TemplateRef" approach is not possible today, see: https://github.com/angular/angular/issues/6163

**Comment by dmdm** [comment]
Maybe Named TemplateRef *is* possible, if template is not inside a template tag.

See this plunk: http://plnkr.co/edit/dXlj6RniRUR12xqQiW3B?p=preview

**Comment by pkozlowski-opensource** [comment]
Things have moved on the ng2 side and the current proposal is to have:

```javascript
@Directive({
    selector: '[ngbTooltip]'
})
export class NgbTooltip {
    @Input() ngbTooltip: string | TemplateRef;
}
```

which means that a user could `<div ngbTooltip="Hey, turn around!">` for simple string-based tooltips or 

```
<template #ttipContent>
   I'e got <b>HTML</b> and {{ng2Stuff}}.
</template>
<div [ngbTooltip]="ttipContent">
```

for more complex scenarios involving HTML and / or Angular directives / interpolation / bindings.

Going to close this one as I think this is a good API to work with. But if anyone has objections - speak up!
