### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/core#15]
Documentation system and site needs to be built.

It needs to support

- [ ] Custom Plunker templates (like currently done on the UI Bootstrap homepage)
- [ ] API documentation of each component
- [ ] Examples of each component

**Comment by Foxandxss** [comment]
Custom plunker is easy, write doc is easy, but we need to figure out where to put it (gh-pages / other place) and if we are going to do something like we did for ui-bootstrap or more modern.

**Comment by wesleycho** [comment]
I'm open to options, as long as it is well argued.

**Comment by suhasdeshpande** [comment]
Dgeni could be another option?

**Comment by Foxandxss** [comment]
No thank you :P

**Comment by pkozlowski-opensource** [comment]
OK, I think that we've got now more focused issues so this one can be closed.
