### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#16]
Apart from components, we need to host tests files and perhaps documentation as well.

So what is the idea you have? Same directory as we had before? A folder for component + folder for tests + folder for docs and demo

**Comment by wesleycho** [comment]
IMO tests should be separate from the core `src` folder - I'm not too religious on this though.

**Comment by BobbieBarker** [comment]
i like Contained directories
i.e
Alert/
alert.tests.ts
alert.ts
alert.html

------

**Comment by Foxandxss** [comment]
at the end of the day, we are picking what files to process by hand, so it doesn't matter what structure we pick.

**Comment by wesleycho** [comment]
Whoever creates the testing harness is the one who gets to choose to start with - let's leave this issue open though afterwards so we can potentially choose how we want it afterwards.

**Comment by Foxandxss** [comment]
Alright, if stuff don't go horribly wrong, I will have testing ready for tomorrow. Changing the folder of tests is 10 seconds.

We will decide then.

**Comment by icfantv** [comment]
My only comment here is that having the templates in a completely separate tree in the NG1 UI BS project is a little silly unless there was a specific design reason for doing so.

I like the idea of having stuff grouped together by component, but i do wonder whether the templates and tests should be in a sub-directory under the main component, ala:

```
alert/
  templates/
    alert.html
  tests/
    alert.tests.ts
  alert.ts
```

Also, on that note, if the test harness supports it, I'd be a HUGE fan of breaking the tests up into smaller pieces.  I found it a bit of a pain in the ass to navigate some of the larger test files in the NG1 version of UI BS.

Is this too cludgy?  Thoughts?

**Comment by Foxandxss** [comment]
We are not discussing templates yet @icfantv. Not for this release.

**Comment by wesleycho** [comment]
One thing we should be aware of is it is general convention in ES6 to have the directories as flat as possible.

**Comment by icfantv** [comment]
@Foxandxss which i would have known had i read today's history.  no worries.

if the convention is for as flat as possible, then i'm cool w/ just the tests being separate - if nothing else, so the jasmin/karma config can reference them easily.

**Comment by Foxandxss** [comment]
Bah, reorganizing this before release is 1 minute job.

/src
--/foo.ts
--/bar.ts

/test
--/foo.spec.ts
--/bar.spec.ts

**Comment by wesleycho** [comment]
Yep, how easy it is to reorganize is why I don't care about this too much to start.

**Comment by BobbieBarker** [comment]
So why not just have it in the same directory and then the build tool just omits tests that are .spec.ts?


Overall agree with wes's sentiments that this is easy to refactor and a semi-null issue. But it's a fun conversation to have about something that is highly subjective.

**Comment by Foxandxss** [comment]
because we are going to have all components in the same folder. If we throw tests in there as well, that is going to be messy.

**Comment by BobbieBarker** [comment]
each component should be in its own dir imo
