### ISSUE TITLE
Accordion refactor: use ContentChildren instead of Query

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#162]
Creating the issue to capture refactorings / changes needed so that we can migrate to `@ContentChildren` usage (in favor of now depreciated `@Query`).

Previous attempts to use `@ContentChildren` wasn't that great as we were going into race conditions. I've got an alternative proposal which:
* doesn't have race condition pbs (or at least I couldn't "break it")
* makes it possible to use panels as stand-alone as well as part of the accordion

Obviously this implementation isn't ideal as we still need better support in the framework for listening to events from children (see: https://docs.google.com/document/d/1335H9D92jo2Xo0g26BhB_nhrNpCTmHsnRr7t50ndH1Y/edit?usp=sharing)

@Foxandxss / anyone interested: could you please have a look at the implementation proposal, before I jump into full-blown impl, tests changing etc.: http://plnkr.co/edit/PZne4mwc0EsGA2Go0JzH?p=preview

**Comment by Foxandxss** [comment]
This works as a temporary workaround until Angular decides to do the ObserveChildren or whatever.

The panel is not generic, it depend on accordion and forces you to have a forwardRef.

Not sure why but I still have in mind that I tried something like this and there was a use case where it blows.

PS: You don't need .toArray() anymore.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss thnx for looking into it.

> This works as a temporary workaround until Angular decides to do the ObserveChildren or whatever.

Definitively, it is not the final impl. 

> The panel is not generic, it depend on accordion and forces you to have a forwardRef.

Totally. But at least a panel can use panels outside of an accordion (see the updated plunker).

> Not sure why but I still have in mind that I tried something like this and there was a use case where it blows.

The use-case I was aware of is the one where there was an `[open]` binding on a panel, but this is covered. 

> PS: You don't need .toArray() anymore.

Right, thnx.

Can I interpret the above as a mild encouragement for a PR?

**Comment by Foxandxss** [comment]
Please go ahead, we are stuck on this for months. We need to move forward and more having ng2 around the corner.

If a better solution arrives, we do it.

**Comment by pkozlowski-opensource** [comment]
Done through b99ca44fc9f9fab638b74430bb36e9723834bfd0
