### ISSUE TITLE
Combine ng2-bootstrap projects?

### ISSUE THREAD

**Issue by linusbrolin** [ng-bootstrap/core#164]
Hi,
I'm not sure if you are aware or not, but there are two separate ng2-bootstrap projects with seemingly the same goal.
[https://github.com/valor-software/ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap)
Wouldn't it be better to combine the efforts into one project?

**Comment by Foxandxss** [comment]
No. We have different goals in mind.

**Comment by mendeza** [comment]
@Foxandxss, I apologize for the question since I know you're very busy, but would it be possible for you to describe the two projects' goals and what you see as the key differences?

**Comment by icfantv** [comment]
@mendeza, There are things at play that it would be unprofessional to get into here.  I will leave it at that.

We are waiting on the angular team to add some features to the library that will make it possible to design certain components correctly.  That said, things are progressing on that front.

**Comment by mendeza** [comment]
@icfantv, I can well imagine. Would it be possible to speak privately? In the past I met with Pawel and Bacon Darwin. I've built a UI framework at Thomson Reuters based on AngularUI-bootstrap. Huge platform products are about to go to market using it. Naturally I'm following the NG2 move with great interest. I also have an army of downstream dev consumers to keep in line. I don't want them getting confused between this project and the "other one." So it would be good for me to get some insight...if it could be arranged in a way that's not indiscreet, inconvenient or uncomfortable for you folks.

**Comment by icfantv** [comment]
@mendeza Understood.  While I appreciate your curiosity, it's not my place to talk about what's going on.

As far as the library is concerned, the biggest issue is that we are waiting on `@ObserveChildren` to properly build the multi-part components - tabs, accordions, etc...  As I said, there's been some movement very recently on this front.

**Comment by mendeza** [comment]
@icfantv OK, no problem. With whom should I speak?

**Comment by wesleycho** [comment]
@mendeza You can find us in Slack on [Angular Buddies](https://angularbuddies.com/) if you'd like to message us directly.

**Comment by DaSchTour** [comment]
Just some points from my perspective. Maybe I'm not the only one.
I've just taken a short look on both projects. And as I've seen this one seams far behind the other project we decided to move on with ng2-bootstrap as we want to release the same day Angular 2 will release a stable version. So we have no time to lose and I have the impression that I can't rely on this project to move fast enough.

**Comment by JohannesRudolph** [comment]
I just wanted to update this to enquire what your view is on how ng-bootstrap differs from ng2-bootstrap? As I see it of today, both projects are fairly complete and neither is official "production ready" which is totally understandable given the current situation with BS4. With angular 2.0 officially released today, I bet many will ask themselves which of the two projects they should use so it would be nice to get an understanding of the differences.

**Comment by icfantv** [comment]
@johannesrudolph, its really going to boil down to a few key things:  code quality and open source philosophy.  The first, you will be able to see on your own, but our desire was to do things the right way in Angular 2 so as to have a clean, maintainable, and extensible library.  The second, we are not trying to promote a business and earn revenue.

The driving member of this project is on the core Angular 2 Google team which gives us a unique position with respect to implementation and insight.  Another member is primarily responsible for writing all the Angular 2 library documentation for Google.  Finally, all the project members use this library at work so we have a real, vested interest in its success and future.

I hope this helps and please don't hesitate to ask us any other questions you might have.

**Comment by JohannesRudolph** [comment]
Thanks, I noticed the code-quality related aspects as well , e.g. ng2-bootstrap doesn't have tests for many modules like the date-picker and has very few tests in general (https://travis-ci.org/valor-software/ng2-bootstrap)

I think this makes ng-bootstrap the more promising long-term option. Will give it a spin!

**Comment by linusbrolin** [comment]
I still wish everyone would have been open to some form of cooperation.
In my opinion, the best scenario would have been ng-bootstrap with contributions from the ng2-bootstrap team (with your code-quality requirements ofcourse!).
Everyone looses on having two competing implementations.
