### ISSUE TITLE
Implementation for Bootstrap 3 AND 4

### ISSUE THREAD

**Issue by squadwuschel** [ng-bootstrap/core#166]
Hi,

currently my biggest problem is that it seems that all new Angular 2 components which are released only support Bootstrap 4. I've a lot of projects where I use Bootstrap 3 and I can't migrate Style and Angular (Code) to a new version and I think there are many other people out there with the same problem.

I would try to use Angular 2 mit ngUpgrade also in older Projects but thats only possible if there is e.g. Ui Bootstrap for Bootstrap 3 with Angular 2.

So it would be really cool if you could provide the new ng-bootstrap for Angular 2 for both Versions of Bootstrap 3 and Bootstrap 4.

**Comment by icfantv** [comment]
@squadwuschel this has already been discussed and currently there are no plans on supporting bootstrap 3.  we have a meeting tomorrow and I will confirm.

**Comment by squadwuschel** [comment]
do you have a link to the issue where this was discussed - I've searched bevore opening this issue but can't find one.

**Comment by Foxandxss** [comment]
There is no public issue on that sorry. We have our own private channel for discussion and we do meetings time to time.

I will bring the topic on today's meeting but the problem we had in the past was not having an easy way to provide multiple templates. We will see.

**Comment by squadwuschel** [comment]
I've found a implementation which supports both templates, but it would be cool if the "original" team for ui bootstrap could implement it, then I feel more confidential about the "support".

https://github.com/valor-software/ng2-bootstrap

this Repository implements both Bootstrap 3 and 4 and so far I can see he can switch templates, but I don't know if this is a good solution.

**Comment by Foxandxss** [comment]
The thing is, BS4 contains the same classes as BS3 so technically what we write could be used with a bootstrap 3 css without any problem.

If we run into template differences and problems, we will discuss what to do, but for now, we have priorities.

**Comment by icfantv** [comment]
@squadwuschel perhaps the BIGGEST problem is that BS3 class structures are very tightly coupled to the DOM.  See [here](https://github.com/twbs/bootstrap/issues/18975) for the issue we filed with bootstrap.  We're talking through ways we might accomplish this.  As I said, we'll discuss at our meeting today.  Ideally, we do not want to have to support multiple templates or multiple code bases...

**Comment by squadwuschel** [comment]
I know that this is not easy and providing multiple code bases are hard to maintain.

But I've talked a lot of to other angularjs developers and the biggest barricade / problem at the moment is that many developers use angular 1 with bootstrap 3 and now bootstrap 4 is released with many styles that are no longer supported in the old version.  And now most of the new angular 2 projects build up on bootstrap 4 - so bootstrap 3 is "dead" and I have no way to constanly upgrade to angular 2 because of my existing code base and projects. I would like to use angular 2 in the feature but thats not possible when all new components only base on bootstrap 4 and I am not alone with this real life scenario - the "Upgrade Hell"

**Comment by RobJacobs** [comment]
Unless I'm mistaken, Bootstrap 4 has not been officially released yet?  According to the TWBS release [page](https://github.com/twbs/bootstrap/releases)  V4 alpha 2 was released on 12/8/2015 with no V4 release since?

**Comment by squadwuschel** [comment]
yes but many new Project for Angular2 like AngularStrap seem to build there new libs directly for Bootstrap 4

**Comment by mendeza** [comment]
@squadwuschel both BS4 and Angular2 are still in beta, and even after beta will not be mature for awhile (esp. Angular2). So imho this project is ahead of the curve to an appropriate extent. Other projects imho have rushed-in too quickly. As a future-facing project, I don't see it as a good allocation of effort to support both BS3 and BS4.
