### ISSUE TITLE
dropdown: more features implemented

### ISSUE THREAD

**Issue by dmdm** [ng-bootstrap/core#169]
Hello,

I have taken the liberty to further implement the dropdown component:
- it uses same attributes as uib-dropdown: "is-open", "auto-close"
- auto-close implemented for "always", "clickOutside", "other_string" (=disabled)
- Always listens to keyboard: impl ESC to close and Enter to toggle
- fixed setting some bs4 css classes

See this plunk: http://plnkr.co/edit/bpM2AW?p=preview

Deviating from what you already had, all 3 selectors are attributes (like uib before), not elements. I hope, I have not violated the spirit of ng2, esp. in the case where global event listeners are involved.

Please let me know if you find this useful, I can provide a PR then.

Best wishes, dmdm

**Comment by dmdm** [comment]
Update: Multiple dropdowns on a page are able to communicate with each other. Currently they tell when one opens, so the others can close. See above plunk for example.

The solution is based on observables and subscriptions and should satisfy your requirements regarding uncoupled components, as mentioned in your ggl doc in #162. Pls see the code comments in "global_messenger" for details.

**Comment by Foxandxss** [comment]
Thanks for the plunker.

Before we decide anything, I want to research better how to make global handlers. I am not really fond of this solution.

**Comment by wesleycho** [comment]
I agree, we need to research this better. In addition, it needs to play well with web workers, service workers, and server-side rendering - this solution does not appear as if it would, but I'm not 100% certain.

**Comment by pkozlowski-opensource** [comment]
Once can easily listen to "global" events by doing `(document:click)="doSth()"`, I don't think we need go down to the renderer level here.

**Comment by dmdm** [comment]
@pkozlowski-opensource Very nice. Could you please point me to some docs.

Playground for this: http://run.plnkr.co/mTnskME8lOa3HQNY/

**Comment by pkozlowski-opensource** [comment]
Reading through this issue we need to review how do we want to handle triggers (both default and custom, open and close). Somehow this issue reminds me the discussion about tooltip triggers we had in  #8 and we probably use the same patterns / solutions.

**Comment by RobJacobs** [comment]
It would be nice to have a trigger service that that could be reused with any component.
