### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by masaanli** [ng-bootstrap/core#195]
When does the doxumentstion of this project releases together with npm packages? (Alpha)?

**Comment by pkozlowski-opensource** [comment]
We can't get specific dates but I'm going to draft a roadmap tomorrow. Will add a link here.

**Comment by pkozlowski-opensource** [comment]
@masaanli sorry that it took me more than one day but we wanted to discuss things internally before we share anything publicly. As I've said we will never commit to any specific dates as there are way to many known unknowns and unknown unknowns on the road ahead. 

What we can share, though, is our plan: https://github.com/ng-bootstrap/core/wiki/Roadmap

I've also created a milestone for the very first initial release that will come with the documentation site: https://github.com/ng-bootstrap/core/issues?milestone=1
