### ISSUE TITLE
docs:  cosmetic cleanup and content

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/core#201]
The following cosmetic cleanups need to happen:
- [x] GitHub button link
- [x] TOC Links to components
- [ ] Additional content for Getting Started Section
 - [ ] Update dependencies (Tether?  Etc...)
 - [ ] Installation instructions
   - [ ] npm
    - [ ] anything else?
 - [ ] Usage/Import instructions
 - [x] Build Instructions
   - [x] Link to DEVELOPER
 - [x] Contribution Instructions
  - [ ] Link to README
   - [x] Link to CONTRIBUTING
 - [x] Code of Conduct
  - [x] Link to CODE_OF_CONDUCT
- [x] GitHub Issue Template
- [x] GitHub PR Template

**Comment by pkozlowski-opensource** [comment]
I don't think "Create a Build" makes any sense given the modularity and shift to npm. Torn on download - but I guess this question would be answered by deciding _what_ we want to publish.  Opened #203 to track content of a release.

**Comment by icfantv** [comment]
@pkozlowski-opensource agreed.  just making _absolutely_ sure.  and thanks for the follow-up.
