### ISSUE TITLE
docs: add component demos

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/core#202]
The following components require demos:
- [ ] Accordion (cleaned up?)
- [ ] Alert
- [x] Buttons
- [x] Carousel
- [x] Collapse
- [x] Dropdown
- [x] Pager
- [x] Pagination
- [x] Popover
- [x] Progressbar
- [x] Rating
- [x] Tabset
- [x] Tooltip

**Comment by pkozlowski-opensource** [comment]
At this point we've got most of the demos in place or PRs opened for the remaining ones (accordion). Some of the existing demos are a bit "light" but we can grow them as we go. I will open separate issues for parts where I believe we can have more / better demos.

In any case I think that we can consider this issue as done.
