### ISSUE TITLE
Discussion: release / npm package content

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#203]
We need to decide what we are going to publish as part of our release:

* [x] ES5 + typings (unbundled)
* [ ] ES6 + typings (esm)
* [ ] ES5  bundle (UMD)

If we are going to publish ES5 we will probably need to limit usage of ES6-specific methods (ones that are not transpiled by TS, ex. Array::every) or advise people to use appropriate polyfills.

**Comment by icfantv** [comment]
per @robwormald, we should ship:

commonJS + d.ts + metadata.json
es6 + d.ts + metadata.json

I don't think we should support ES5.  Especially if Angular isn't going to...

**Comment by pkozlowski-opensource** [comment]
I'm confused... What `commonJS + d.ts + metadata.json` supposed to be? Isn't it ES5?

Regarding ES5 - what is the cost of "supporting" it? Isn't it about having one run of build tool?

**Comment by icfantv** [comment]
@pkozlowski-opensource I just posted what rob said, but you're right, if it's just a build tool run....

Probably worth a discussion.  Check out the thread on slack (#ng-2 channel).

**Comment by pkozlowski-opensource** [comment]
OK, so as a very minimum we should release what gets produced in `dist/cjs` after running `gulp build` task. For this we need to create a package.json.

**Comment by wesleycho** [comment]
I thought Angular supports ES5? Did something change?

**Comment by pkozlowski-opensource** [comment]
I think we've got it figured out. The latest decision is to do what `@angular/core` is doing which means:
* un-bundled ES5 + typings + source maps in the root of the package (modules transpiled to CJS) 
* un-bundled ES6 + typings + source maps in the`esm` subfolder (modules transpiled to ES6)
* ES5 UMD bundle in the `bundles` subfolder

@Foxandxss if I understand correctly you are going to take care of the build changes to reflect this, right?
