### ISSUE TITLE
Alert: support for self-closable alerts

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#206]
As described in https://github.com/ng-bootstrap/core/issues/2#issuecomment-218851066

**Comment by pkozlowski-opensource** [comment]
OK, so after chatting with different people in the Angular team, here is my proposal:
* let's keep the current alert component as is - it will serve as a "static" component that people can use in various situations
* let's add another directive that could be used like so:

```html
<template ngbAlert>
   Alert's content
</template>
```

By putting alert on a template element we make it clear that it can be dismissed / destroyed it in the way that doesn't leave any traces in the final DOM. Adding support for dismissing on timeout would be trivial as well.

Implementation should be super-simple, here is a sketch of it (it still needs wiring-up inputs / outputs):

```javascript
import {Directive, TemplateRef, ViewContainerRef, ComponentFactory, ComponentResolver, Injector} from '@angular/core';
import {NgbAlert} from './alert';

@Directive({
  selector: 'template[ngb-alert]'
})
export class NgbAlertDismissible {
  constructor(private _vcRef: ViewContainerRef, private _tplRef: TemplateRef<any>, private _cr: ComponentResolver, private _injector: Injector) {
  }

  ngOnInit() {
    this._cr.resolveComponent(NgbAlert).then((cf: ComponentFactory<NgbAlert>) => {
      var rootNodes = this._tplRef.createEmbeddedView({}).rootNodes;
      this._vcRef.createComponent(cf, 0, this._injector, [rootNodes]);
    });
  }
}
```

Thoughts? I would gladly prepare a PR for the above, but unfortunately testing of this kind of functionality is blocked by https://github.com/angular/angular/issues/8617

**Comment by wesleycho** [comment]
How would a user dismiss the alert?

Works for me - also, I think that selector should be `template[ngbAlert]`
