### ISSUE TITLE
Tabset: use user-defined ids / indexes instead of array indexes

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#215]
See: http://angular-ui.github.io/bootstrap/#/tabs

**Comment by pkozlowski-opensource** [comment]
There are couple of API options I would like to discuss here before we dive into implementation. 

To start with, today we are using a numeric index of a tab to manage an active tab. This is obviously not great since change in the tabs collection (ex. first tab removed by `ngIf`) might change an active tab. So instead of using indexes in an array of tabs we should be using user-supplied indexes. As such the API should change from today's:

```html
<ngb-tabset [activeIdx]="2">
    <ngb-tab>...</ngb-tab>
    <ngb-tab>...</ngb-tab>
    <ngb-tab>...</ngb-tab>
    ....
</ngb-tabset>
```

we should change to sth like:

```html
<ngb-tabset [activeIdx]="myIdx2">
    <ngb-tab index="myIdx0">...</ngb-tab>
    <ngb-tab index="myIdx1">...</ngb-tab>
    <ngb-tab index="myIdx2">...</ngb-tab>
    ....
</ngb-tabset>
```

Obviously some people might not care about having programmatic tab selection so we should mark `index`  as optional and generate it when not supplied. 

Given all the above I would like to discuss couple of options:
* shell we use `[index]` or `[id]` on a tab level? `[id]` seems more HTML-ish somehow...
* if using `[id]` shell we reflect them in the DOM (probably yes, but then those should be unique)

Thoughts?

**Comment by pkozlowski-opensource** [comment]
My vote goes to using `id` as we will need for accessibility as well, see: #230

**Comment by sendilkumarn** [comment]
@pkozlowski-opensource  too agree on id and we should be having a default id and use it if there is no id available.

**Comment by icfantv** [comment]
per recent issues in UIBS, we should support both strings and integers as `index` values.

**Comment by pkozlowski-opensource** [comment]
@icfantv I'm not even sure if this makes sense to support numbers at all. Anyway, what I was trying to capture in this issue was more naming (`index` vs. `id`)

**Comment by icfantv** [comment]
ok.  my intent was not to hijack - only to mention issues from UIBS.
