### ISSUE TITLE
chore: API extraction script - convert tests from mocha to jasmine

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#223]
[This test](https://github.com/ng-bootstrap/core/blob/master/misc/api-doc.spec.js) uses mocha+chai, we should convert it to Jasmine to use only one testing framework for node and browser.

**Comment by sendilkumarn** [comment]
Am wondering how to test this one after changing api-doc.spec.js? Any help to validate?

**Comment by pkozlowski-opensource** [comment]
> Am wondering how to test this one after changing api-doc.spec.js? Any help to validate?

Not sure I understand the question. We should just convert https://github.com/ng-bootstrap/core/blob/master/misc/api-doc.spec.js from using mocha to Jasmine. So this is all about mocha -> jasmine syntax changes + npm dependency changes. Semantic of the existing test should remain exactly as it is today.

**Comment by sendilkumarn** [comment]
I converted it. But how to run it?

Seems like karma tests are not included for this?

**Comment by pkozlowski-opensource** [comment]
> Seems like karma tests are not included for this?

Those are node tests, not browser-based tests so Karma has nothing to do here. 

> But how to run it?

No idea, never used Jasmine on node :-) Part of this issue is to figure this thing out!

**Comment by pkozlowski-opensource** [comment]
Closed by 3de87fc7a87d7d71d06969dae78ed3b1899d1260
