### ISSUE TITLE
Carousel: add keyboard navigation + tests

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#232]
It is about the `keyboard` option from http://v4-alpha.getbootstrap.com/components/carousel/

Check https://github.com/ng-bootstrap/core/blob/7ae57e3ee5737e12e3a53e534bc98acfff391663/src/dropdown/dropdown.spec.ts#L112-L132 for an example of testing with keyboard events.

**Comment by sendilkumarn** [comment]
Is this enough or am I missing anything...? 78e0a9ca35deca6cdede0d63325d8ba3062a8528

**Comment by sendilkumarn** [comment]
Adding a host event would be enough right? 

Something like this 78e0a9c

**Comment by pkozlowski-opensource** [comment]
> Adding a host event would be enough right?

Did you test it outside of unit tests, in a real app? Things from your commit should be enough but we need to make sure that the carousel can be focused to actually receive key events (tabIndex?)

**Comment by pkozlowski-opensource** [comment]
Landed via 01b0542c213f9719312e90db9bebd7a8a1256731
