### ISSUE TITLE
Demo site: switch to the latest router

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#234]
https://github.com/angular/vladivostok

**Comment by Foxandxss** [comment]
I can do that.

**Comment by pkozlowski-opensource** [comment]
> I can do that.

@Foxandxss this would be awesome!

**Comment by pkozlowski-opensource** [comment]
Please note that this blocks update to RC.3 so it kind of raises priority of this one.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss did you test the demo site after update to rc.3? On my side doing `gulp demo-server` gives me: 

> ERROR in ./demo/src/vendor.ts
Module not found: Error: Cannot resolve module '@angular/router-deprecated' in /xxx/core/demo/src
 @ ./demo/src/vendor.ts 7:0-37
