### ISSUE TITLE
Timepicker:  implementation discussion

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/core#242]
Just documenting this so we don't lose it.  Per issues (and @wesleycho) in UIBS library, we should manage the hours, minutes, and second fields separately and not use a date object to back the data.   This does mean we need to handle the rolling ourselves, but I'm ok with that.

This also allows us to make a duration picker (using a common base) as well as people have asked for this in the UIBS library.

**Comment by pkozlowski-opensource** [comment]
@icfantv I'm going to move your comment to #24 - no need to keep it as a separate issue for now.

**Comment by icfantv** [comment]
@pkozlowski-opensource no worries, mate.  too many issues to keep track of - easy to have dupes.
