### ISSUE TITLE
Progressbar

### ISSUE THREAD

**Issue by wesleycho** [ng-bootstrap/core#25]
Implement progressbar from UI Bootstrap/Bootstrap 3

**Comment by Foxandxss** [comment]
Does this directive makes any sense? Checking BS4 docs, I am not sure what can we provide.

**Comment by pkozlowski-opensource** [comment]
AFAIK we need a directive if we want to support browsers that don't have `<progress>` element support.

I've got a simple impl here: https://github.com/pkozlowski-opensource/ng2-bs/blob/master/src/progress/progress.ts

**Comment by Foxandxss** [comment]
Nice @pkozlowski-opensource. You want to tune it up and make a PR or do you want me to do it?

**Comment by pkozlowski-opensource** [comment]
Yep, the plan is to make a PR. I will do it over the weekend as I'm running a training right now (Wed-Fri) so can't do much in therms of OS work (other than commenting on some issues :-))

**Comment by pkozlowski-opensource** [comment]
Updated WIP here: https://github.com/pkozlowski-opensource/ng2-bs/blob/master/src/progress/progress.ts

**Comment by Foxandxss** [comment]
I'm working on this too. It doesn't make sense on the way you have it.

We need to reuse the built-in progressbar and decorate it with an attribute
directive. I have a plunker with my ideas, will link later, so hold on this
one.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss it needs to work in all browsers supported by ng2 so I don't think we can just use `<progress>` element as it doesn't work in all browsers

**Comment by Foxandxss** [comment]
IIRC it does work in all our supported browsers. We can do it without it,
but adds lots of extra complexity.

For example, making it stripped, would require to copy the ngb-progressbar
classes,  to put it on our template.

Would be good to investigate the built in support.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss If you believe that there is a better approach, feel free to take ownership of this one.

**Comment by Foxandxss** [comment]
Let me do some demos so we can discuss it.

I have something half baked on a plunker. Will also try to do the striped
thing with your implementation and see which one makes more sense on the
long term :)

**Comment by Foxandxss** [comment]
No ie9 support for the built in one. Grrr. Forget what i said

**Comment by Foxandxss** [comment]
Or not, bs4 have instructions to fix it out which could be good for what I have in mind. Let me do that plunker.

**Comment by Foxandxss** [comment]
Okey, here it is: http://plnkr.co/edit/YtyckNLh6vOwLfl1OyHE?p=preview

Both have their "things", but I Think that I definitely go with the element one and not the attribute one (less verbose). Problem is the nativeElement thingy which is no good.
