### ISSUE TITLE
Demo site deployment decissions

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#253]
There are few things we need to determine before we can deploy the demo site:
* [x] place to deploy (gh-pages?) => https://github.com/ng-bootstrap/ng-bootstrap.github.io
* [x] url => we've got ng-bootstrap.io domain 
* [x] location strategy for router links (can we use HTML5 mode?) => hash
* [x] versioning of docs (do we have a separate folder per version from the day 0?) => not before 2.0.0

Maybe there are other items but at least the above need to be sorted out.

**Comment by icfantv** [comment]
If we can swing it, I think we do doc versioning right out of the gate.  @Foxandxss set it up on UIBS and I don't think it took him very long.  The one thing will be how many previous versions do we maintain?  I believe Angular only ever shows the latest patch revision for each major/minor release.

**Comment by pkozlowski-opensource** [comment]
I think that we've figured out most of the deployment decisions. I vote for not versioning docs till we gat to the final (or at least rc) release.
