### ISSUE TITLE
docs: add API docs

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#264]
The following components API docs:
- [x] Accordion
- [x] Alert
- [x] Buttons
- [x] Carousel
- [x] Collapse
- [x] Dropdown
- [x] Pager
- [x] Pagination
- [x] Progressbar
- [x] Rating
- [x] Tabset

**Comment by sirajc** [comment]
I can pick up docs for collapse.
Will have two examples, one Basic and other with default close
Something similar to this old plunker
http://plnkr.co/edit/SW68aAIMP6iwVtNUZZis?p=preview

@pkozlowski-opensource Let me know if I should proceed

**Comment by icfantv** [comment]
@sirajc i would say go ahead and please submit a PR and we'll do it iteratively.  we had a meeting yesterday and the demos should be structured as the alert demo:  most simple/basic first, the more advanced as appropriate.

to be clear, we don't want 10 demos, but we want to showcase the different possibilities as applicable.  additionally, we want 100% API coverage in the demos, meaning, across all the demos, we are using (demoing) every public API property/component.

**Comment by sirajc** [comment]
Thanks @icfantv , I am following every bit of alert demo structure. There is nothing much in Collapse so 2 demos is sufficient one basic and one showing the usage of default value. 
Will raise a PR and then we can discuss on it further, I am open to discussions and consume feedback so no worries on number of iterations

**Comment by maxokorokov** [comment]
@pkozlowski-opensource any ideas on how to handle default values for accessors to private variables? I mean this:

```javascript
class Pagination {
  private _page = 0;
  
  /**
  * Comment goes here, but what's the default value?...
  */
  @Input() set page(value: number | string) { ... }
}
```

Can't find simpler solution than adding it directly, even though the value is in two places in this case...

```javascript
  /**
  * Comment goes here, but what's the default value?...
  * @default 0
  */
```

**Comment by pkozlowski-opensource** [comment]
@maxokorokov hmmm, we don't support it right now with the default API extraction in place. Could you please add this use-case to #222?

In your particular case `0` is an implementation detail (somehow) so not showing default value won't do much harm. But yeh, we need to support this....

**Comment by wesleycho** [comment]
Going to close this, this looks done minus pending PRs
