### ISSUE TITLE
chore(docs): doc fixes based on UX feedback

### ISSUE THREAD

**Issue by icfantv** [ng-bootstrap/core#270]
- [x] more space between sections
- [x] directive name should look like a hyperlink
- [x] fix the logo as it's in a different color

**Comment by icfantv** [comment]
This is currently blocked on #269.

**Comment by sirajc** [comment]
We can add `[routerLinkActive]="['active']"` for all _routerLink_ in side-nav.component.html. Create active class in `styles` of side-nav.component.ts, to highlight current directive by making it bold or darker

**Comment by pkozlowski-opensource** [comment]
@sirajc yes, we should do it 👍

**Comment by Foxandxss** [comment]
As a note, we can do `routerLinkActive="active"` or something like that. For some reason I don't see the API listed at angular.io. Weeird.

**Comment by sirajc** [comment]
I had tested `routerLinkActive` locally for demo site, it works great  
Will style active as bold for now, then change as per feedback, should I create a PR ?

**Comment by pkozlowski-opensource** [comment]
@sirajc go ahead and create a PR so we can discuss with more concrete example. Thnx!
