### ISSUE TITLE
demo site: switch router to hash location strategy

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#293]
Since we are going to deploy to gh-pages where we can't have server side redirections we need to stick with the hash location strategy. It should be a very simple fix, essentially the same as in https://github.com/angular/angular2-seed/blob/452d6daad7c024860d9c84947a812ce4cbcb1910/src/main.browser.ts#L14

**Comment by Foxandxss** [comment]
Yes, I can do that.
