### ISSUE TITLE
beta.0 (Future-complete). Do you mean feature-complete here?

### ISSUE THREAD

**Issue by otabekgb** [ng-bootstrap/core#296]

**Comment by pkozlowski-opensource** [comment]
Check https://github.com/ng-bootstrap/core/wiki/Roadmap. let me know if things are unclear after reading through it.

**Comment by otabekgb** [comment]
I mean the spelling. Shouldn't future-complete be feature-complete?

**Comment by pkozlowski-opensource** [comment]
Oh, right, I see :-) Fixed spelling, thnx!
