### ISSUE TITLE
ng-bootstrap may be a misleading name, probably use ng2-bootstrap

### ISSUE THREAD

**Issue by daixtrose** [ng-bootstrap/core#305]
I would like to point you to the issue that discriminating libraries for Angular 1 from Angular 2 is a tough task when doing a web research. What I found helpful was that people start to name their Angular 2 libraries using the pattern `ng2-<some name here>`

This helps a lot. Now I can search for "ng2-" on GitHub and find libraries compatible with Angular 2 out of the box. 

What do you think? Is it possible for you to rename this library?

**Comment by Foxandxss** [comment]
There is already a `ng2-bootstrap` and personally I don't think the naming is that important.

**Comment by wesleycho** [comment]
Yeah, this would actually increase confusion as there is an ng2-bootstrap already. Also this would be hugely problematic if Angular bumps up to 3 (and follows semver for example).

**Comment by pkozlowski-opensource** [comment]
@daixtrose yeh, this is unfortunate but I don't think it is limited to this library. For quite some time community as the whole will have to figure out if a given library is for Angular 1 or Angular 2....

As @Foxandxss and @wesleycho pointed out there are multiple initiatives around Angular 2 + Bootstrap and number of "obvious" names is limited. While I believe that several competing (constructively!) libraries is a "good thing" I can see how this can create confusion for the community. 

It would be great if we could just one perfect library with obvious name, this is not where we are right now. But I would like to take this as on occasion to extend our invitation to contribute to this repo. We will always value quality contributions!
