### ISSUE TITLE
Pagination: add directionLinks input

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#315]
Very similar to how we handle `boundaryLinks` here: https://github.com/ng-bootstrap/core/blob/fb4d331443f48321826d09a2292d3bd68ae21168/src/pagination/pagination.ts#L10

**Comment by maxokorokov** [comment]
@pkozlowski-opensource I think with the difference that direction links should be shown by default, right?

**Comment by pkozlowski-opensource** [comment]
> with the difference that direction links should be shown by default

Exact.
