### ISSUE TITLE
Positioning: changes suggestions

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#334]
* [ ] - is there any particular reason for `Positioning` to be a class? Could we just export `positionElements` function?
* [ ] - Could `positionElements` actually apply calculated positioning values to a target element? I think that in the past we were not doing this due to testing, but since now we are testing with the live DOM anyway....

Disclaimer: I don't know much about the current code in the positioning service and I'm not suggesting that we should make changes, just asking questions :-)

**Comment by RobJacobs** [comment]
I was thinking we could use the Positioning service to expose some of the methods so folks building their own directives could re-use our code.

Not applying the calculated positioning values makes the method more flexible as folks may want to just get what the positioned values would be and use them how they see fit (add some margin, use the values to calc if the element fits in the viewport).

**Comment by pkozlowski-opensource** [comment]
Going to close for now, will see how things turn out in the future.
