### ISSUE TITLE
Dropdown: dropdown-menu is not properly aligned with dropdown-toggle button

### ISSUE THREAD

**Issue by sendilkumarn** [ng-bootstrap/core#361]
<img width="598" alt="screen shot 2016-07-05 at 8 33 19 pm" src="https://cloud.githubusercontent.com/assets/12471122/16584650/bbf76dec-42ef-11e6-9ea4-b1c2cb55a5dc.png">

**Comment by pkozlowski-opensource** [comment]
Could you reproduce it in a plunker? I suspect that this is something demo-specific.

**Comment by sendilkumarn** [comment]
I will try to do on plunker.

I have a question, class="dropdown" has to be generated by the component right for ngb-dropdown elements?

**Comment by pkozlowski-opensource** [comment]
Fixed by 25675034cde890894f11812805e14c33ef96b00d
