### ISSUE TITLE
Demo page does not response. - https://ng-bootstrap.io/getting_started

### ISSUE THREAD

**Issue by jin-chong** [ng-bootstrap/core#377]
### Bug description:
Demo page "https://ng-bootstrap.io/getting_started" does not response, and browser shows me error 'ERR_CONNECTION_TIMED_OUT'

### Link to minimally-working plunker that reproduces the issue:
N/A
### Version of Angular, ng-bootstrap, and Bootstrap:

Angular:
N/A
ng-bootstrap:
N/A
Bootstrap:
N/A

Thanks!

**Comment by icfantv** [comment]
@jin-chong, Thanks for the interest in our project.  I'm not sure we've actually launched the site yet.  The current plan is to try and launch our first alpha release this week (which includes the site).  So please stay tuned.  Thanks.

**Comment by icfantv** [comment]
@jin-chong, so i was partially right.  while i was correct in that it's not actually launched/deployed yet. the URL is working, but not over `https` as I've been told GH doesn't support that for custom domains, apparently.  HTH.
