### ISSUE TITLE
Accordion extra features

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#49]
The accordion is missing:

- [ ] All the accessibility
- [ ] Be able to use HTML on the header.
- [x] Swap hidden for collapse.
- [x] Use ContentChildren instead of Query.
- [ ] Remove circular deps
- [x] See if it is feasible to create a generic panel from the groups.
- [ ] Change API of `isOpen`.

**Comment by wesleycho** [comment]
We could do a named ng-content element with `select` usage, i.e.
`<ng-content select="ngb-accordion-heading"></ng-content>`

Then it would be used like
```html
<ngb-accordion>
  <ngb-accordion-group>
    <ngb-accordion-header>Foo</ngb-accordion-header>
    <ngb-accordion-content>Bar</ngb-accordion-content>
  </ngb-accordion-group>
</ngb-accordion>
```

**Comment by Foxandxss** [comment]
Yup, that was already in my mental todo list. But before I want a 100% (or the closest we can) test coverage for what we have already. Before accordion grows too much and we lose the track of what we need to test yet.

**Comment by pkozlowski-opensource** [comment]
Closing in favor of more focused issues I've just opened.

**Comment by azarus** [comment]
Any chance we could have it any soon?
