### ISSUE TITLE
Linting?

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#63]
I saw that the angular repo is using TSLINT for linting.

We have clang, but clang is not a linter. Stuff like semicolons are not being processed by clang.

To add this, I would need, yet again, reestructure the tooling so linting can be run on the build, travis...

WDYT?

**Comment by pkozlowski-opensource** [comment]
+1 for linting. But we need to re-shuffle our build first. IMO the current split of tasks between package.json and gulpfile doesn't make things clear / easy to evolve.

**Comment by Foxandxss** [comment]
I totally agree Pawel. Wes suggested dropping gulp and go fully webpack, which I totally agree. The problem is that I didn't see how to properly run clang via CLI (so I can do a npm script with that).

What do you think? Try to move more to package.json or move more to gulpfile?

Both have their good and bad parts.

**Comment by pkozlowski-opensource** [comment]
> Wes suggested dropping gulp and go fully webpack, which I totally agree

I think that we need to have a conversation here :-) I'm fine with using webpack to prepare dist bundles, but I'm not sure it is the right fit for the entire build.

> What do you think? Try to move more to package.json or move more to gulpfile?

My vote would go for gulp (probably starting with gulp 4 if we can)

**Comment by Foxandxss** [comment]
Oh, let me research the gulp 4 thing.

We need that conversation for sure. *cough* slack *cough*.

**Comment by wesleycho** [comment]
I'm not hugely opinionated on the tooling, so I'm fine with keeping it mostly gulp.

I'm a big fan of linting though.

**Comment by Foxandxss** [comment]
With tooling in place, I will do this soon

**Comment by pkozlowski-opensource** [comment]
Fixed by 8013e7bf1419d3cea98ea949378e701f9a17bff6
