### ISSUE TITLE
Folder organization and file naming

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#64]
Could we discuss a slightly different organization of our folders? My main motivation here is to have files that change together go together. In this spirit I would propose (an example for one component):

```
src
    rating
        rating.ts        
        rating.spec.ts
    core.ts
```

How does it sound?

**Comment by Foxandxss** [comment]
I had in mind something like we have in uibs (including a docs folder). But since I haven't thought about docs yet, I am not sure what am I going to need, so, so far, I agree with this config you say. I can refactor tooling for that tomorrow.

**Comment by pkozlowski-opensource** [comment]
IMO docs could go into the same folder as well. 

> I can refactor tooling for that tomorrow.

This would be awesome! I'm going to continue looking at the existing code in the meantime!

**Comment by Foxandxss** [comment]
I am peeking gulp 4 (which doesn't seem that active), and see if I can make the tooling better.
