### ISSUE TITLE
Code conventions

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#67]
I don't want to have each to be different, so I have some points to discuss.

I recently saw egghead videos, and I found an interesting pattern, you can do something like:

```
<my-dir #my-dir></my-dir>
{{myDir.someinnerstuff}}
```

That strikes me a bit, you know, encapsulation and not letting inner details to be usable from outside, but I am not sure if this is going to be a common pattern in Angular so we should allow this. Well, I don't think we have a choice, but this drives me to the next point.

Inner variables on our component, underscored or not?

```
_foo: string;
```

vs:

```
foo: string;
```

I can see the first pattern, but if allowing it from outside will be common, perhaps that is a weird pattern, or perhaps not (like saying, sure, use it but you shouldn't.

Another point is:

```
foo = 0;
```

Typescript will type it as a `number` automagically (because you initialize it). Should we put `number` nonetheless?

When to use private? For example of the `pagination` directive, we have private on a underscore method but not in the variables. For what I see on the wild, they don't use private that much, so I am not sure what to say about this.

**Comment by Foxandxss** [comment]
Personally, I like what @pkozlowski-opensource did on pagination, but I would add more typing (even if it is not really needed). Like those number variables that are initialized but they don't have typing.

**Comment by Foxandxss** [comment]
Tests conventions:

I think we should write two big describe blocks. One to test the directive behavior (without UI) like we used to do with Angular 1 and then another big describe block to test the UI too.

What do you thing? We should do the same for all of them, so better if we lay some conventions.

**Comment by pkozlowski-opensource** [comment]
@Foxandxss you are raising many valid points here but IMO it would be easier to discuss those if we would have a separate issue for each point (and a label to find all those issues)

**Comment by Foxandxss** [comment]
What do you suggest? An issue for component conventions and another one for test conventions?

To be honest, I don't think one issue like this is too messy. We just need to settle some basic conventions between us so our component and tests follow the same ideas.

**Comment by pkozlowski-opensource** [comment]
> What do you suggest?

One issue per item to discuss. I can see 4 separate issues here :-) 

> To be honest, I don't think one issue like this is too messy

I'm not saying it is messy - I'm just saying it would be far easier for me to focus on individual items rather that having a conversation about everything in one issue.

**Comment by Foxandxss** [comment]
Sure mate, will do that right now.
