### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by BobbieBarker** [ng-bootstrap/core#7]
Recreate BS3 Tab with ng2 component

**Comment by pkozlowski-opensource** [comment]
After much discussion with Misko and based on the experience from handling accordions, here is the API proposal for tabs: http://plnkr.co/edit/EkhG7qdq65HQaCAwpAyx?p=preview

WDYT? To implement it properly we would need `ngInsert` type of a directive and I could have it landed in core withing a week (at least this is my hope).

**Comment by pkozlowski-opensource** [comment]
Other open question would be about an open tab. In angular-ui/bootstrap we've got "isOpen" flag on each tab but it doesn't make much sense since at most one tab can be open at a time. So I'm thinking more and more about having an "activeTab" property on the tabset level. Not sure though if it should point to a tab instance, index of it or something else?

**Comment by icfantv** [comment]
We just switched 1.x over to this design.  I'm ok with the active tab being on the tabset element.  We should support numeric and string index values.

**Comment by pkozlowski-opensource** [comment]
> We just switched 1.x over to this design. I'm ok with the active tab being on the tabset elemen

Good to know!

> We should support numeric and string index values.

@icfantv I was actually thinking of using tab references as indexes (super easy to do in ng2)

**Comment by icfantv** [comment]
Oooo, I like that even better.

**Comment by pkozlowski-opensource** [comment]
Sooo, I need you guys to help me to decide on the API for tabs. 2 options I'm considering:

Option (1):

```HTML
<ngb-tabset>
    <ngb-tab [title]="Foo">
         <template ngb-tab-content>Foo content</template>
    </ngb-tab>
    <ngb-tab>
         <template ngb-tab-content><b>Bar</b></template>
         <template ngb-tab-content>Bar content</template>
    </ngb-tab>
</ngb-tabset>
```

Option (2):

```HTML
<ngb-tabset>
    <ngb-tab [title]="Foo">
         Foo content
    </ngb-tab>
    <ngb-tab>
         <template ngb-tab-content><b>Bar</b></template>
         Bar content
    </ngb-tab>
</ngb-tabset>
```

Option (2) is simpler but Option (1) gives us opportunity to have "lazy" tabs - that is, render only visible content.

WDYT?

**Comment by Foxandxss** [comment]
Can't we have both?

**Comment by pkozlowski-opensource** [comment]
> Can't we have both?

We could have 2 different sets of components / directives. I wouldn't know how to mix & match 2 strategies in one component.

**Comment by Foxandxss** [comment]
Why the second one has a template btw?

And I don't know about the implementation so no idea what difficulties they have.

**Comment by wesleycho** [comment]
What advantage do we get from multiple tab contents inside a tab?

**Comment by pkozlowski-opensource** [comment]
> What advantage do we get from multiple tab contents inside a tab?

As long as sth is inside a template tag it is innert (no change detection, no directives processed etc.). Which means that for "big" tabs we could process content of an active tab only, instead of processing / dumping in the DOM content of all tabs (visible or not). 

So it feels like perf vs. nice API

**Comment by wesleycho** [comment]
Well, I meant more couldn't it be all contained in one `<template ngb-tab-content>`? I'm a bit confused here

**Comment by pkozlowski-opensource** [comment]
> Well, I meant more couldn't it be all contained in one <template ngb-tab-content>? I'm a bit confused here

Oh, I see, my example had a typo which made things confusing, sorry for this. Corrected. It should read:

````html
<ngb-tabset>
    <ngb-tab [title]="Foo">
         <template ngb-tab-content>Foo content</template>
    </ngb-tab>
    <ngb-tab>
         <template ngb-tab-title><b>Bar</b></template>
         <template ngb-tab-content>Bar content</template>
    </ngb-tab>
</ngb-tabset>
````

**Comment by wesleycho** [comment]
Ah, that makes a lot more sense - I like that

**Comment by pkozlowski-opensource** [comment]
> Ah, that makes a lot more sense - I like that

So would you go with (1) or (2)?

**Comment by Foxandxss** [comment]
1 is more interesting.

**Comment by pkozlowski-opensource** [comment]
Thnx @wesleycho and @Foxandxss for your comments. If I don't hear more feedback till Mon I will start implementing (1).

**Comment by bekos** [comment]
@pkozlowski-opensource I know mixing templates with directives has some issues  (that I hope to be solved from the core at some point soon) but a syntax similar to what it's there today, on angular's site and ngb1, wouldn't be more intuitive:
```html
<ngb-tabset>
    <template ngb-tab [title]="Foo">
         Foo content<
    </template >
    <template ngb-tab>
         <template ngb-tab-title><b>Bar</b></template>
         Bar content
    </template>
</ngb-tabset>

```

**Comment by pkozlowski-opensource** [comment]
@bekos I'm not sure it will work - or at least would require some hacks. The thing is that a template is innert so `ngb-tab-title` would only "wake up" when `ngb-tab` is stamped out. This might be too late or at least require work-arounds to get the timing right.

In any case I think that the current mental model behind querying / stamping out children is way too simplistic and inconsistent. IMO this is one of the main things to address in the core and this is why I'm going to prioritize this when talking to Misko.

**Comment by bekos** [comment]
Sorry being late on this, but now that `ngTemplateOutlet` and https://github.com/angular/angular/commit/d2efac18ed592b020a3f5d37a72e443a4efbb836 has landed on core, maybe an API like this could work also:

```html
<ngb-tabset>
    <template ngb-tab [title]="Foo">
         Foo content
    </template>
   <template #myFancyTiltle><b>Bar</b></template>
    <template ngb-tab  [title]="myFancyTiltle">
         Bar content
    </template>
</ngb-tabset>
```

@pkozlowski-opensource What's your opinion?

**Comment by pkozlowski-opensource** [comment]
@bekos - not sure. What "disturbs" me is that title element is outside of a given tab. I think that we can easily support what you are proposing as an option (in this case a title could be either a string or a TemplateRef).

Honestly I don't have strong opinion on this API, I would wait and see what works in practice and what users are saying.
