### ISSUE TITLE
Convention: prepend underscore on variables

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#73]
Should we prepend variables like:

```
class Foo {
  _foo;
  _bar;
}
```

The way to work with components is to create a setter for inputs, that way we can keep or component updated with changes, for example:

```
@input
set foo(value) {
  this._foo = value;
  // do something
}
```

So far so good, but you can use this like:

```html
<foo #foo></foo>
{{foo._foo}}
```

So if we decide to go with underscores, we will have that syntax, our we could create a getter.

**Comment by Foxandxss** [comment]
Personally, I like underscore for the things that have a setter (not for everything) and for the usage like I put at the end, well, use the underscore as well.

**Comment by pkozlowski-opensource** [comment]
Yeh, I was mainly adding those underscores for cases where we need a setter. But I'm fine with using any prefix / suffix for this case.

**Comment by Foxandxss** [comment]
I am good with underscores, classic convention, but only when it has a setter for it, if it doesn't have a setter, I vote for no underscore at all. For example, in your pagination, `_pages` has no setter.

**Comment by pkozlowski-opensource** [comment]
I think that we are on the same page here.

**Comment by Foxandxss** [comment]
Ok, so no underscore for `pages` in there. And if the user wants to get a ref of our element and use some internal values, he will need to check the source to see if what he wants to use has underscore or not. Not really fond of forcing to read the source, but I don't like having to create getters to just for that.

**Comment by pkozlowski-opensource** [comment]
Yeh, you are raising a valid point which I kind of bumped into while doing testing. Maybe having "public" getters wouldn't be such a bad idea, after all?

**Comment by Foxandxss** [comment]
`get pages() { return _pages; }`

Not a big deal, just extra code to maintain. But will definitely help end users with all their use cases, not having to use _ if they do the ref thing.

**Comment by pkozlowski-opensource** [comment]
>  But will definitely help end users with all their use cases, not having to use _ if they do the ref thing.

It would make our templates "prettier" as well.

**Comment by wesleycho** [comment]
So question - if we have 
```js
get bar() {
  return this._bar;
}

@input
set bar(value) {
  this._bar = value;
  // do something
}
```
Then will it be consumable like
```html
<foo #foo></foo>
{{foo.bar}}
```
?

It seems a bit awkward to have to consume with an underscore prefix IMO, since a lot of conventions use it as a way of denoting private properties.

**Comment by Foxandxss** [comment]
Yes, that is absolutely correct.

**Comment by pkozlowski-opensource** [comment]
OK, so if I understand things correctly, the summary here could be: if there is a sett for the `foo` variable then:
* store the actual value in the `_foo` variable (and mark it as private?)
* create a corresponding getter

Is it about right?

**Comment by Foxandxss** [comment]
Yes to all. I will add the summary at the top of each issue in a bit.

**Comment by Foxandxss** [comment]
Well, lies, I will create a FAQ document with all the conventions.

**Comment by pkozlowski-opensource** [comment]
> Well, lies, I will create a FAQ document with all the conventions.

Cool! Like WIKI? We should share those with the ng team at Google at some point so we can check with them / enforce those for other widget libraries as well.
