### ISSUE TITLE
Convention: explicit or implicit typing

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#74]
Something like:

`let foo = 0;`

is already a `number` variable, it is implicit due to initialization.

Should we rely on that or should we:

`let foo:number = 0;`

**Comment by Foxandxss** [comment]
I personally vote for explicit.

**Comment by pkozlowski-opensource** [comment]
My vote goes to `let foo = 0;` - I don't like to repeat things that are implied by context / conventions. But I can perfectly live with any of the 2 approaches.

**Comment by Foxandxss** [comment]
So implicit when you initialize and explicit when you don't, right?

**Comment by pkozlowski-opensource** [comment]
> So implicit when you initialize and explicit when you don't, right?

Yes. Then again, either way forks for me here

**Comment by wesleycho** [comment]
I prefer implicit here - with TypeScript, if you try to override the variable with a new type, it throws on compilation, so if a user is familiar with TS, it will become obvious that the type is a number for that example.

**Comment by Foxandxss** [comment]
Ok. this one is settled.

**Comment by Foxandxss** [comment]
Not settled. There is one corner case:

```
let arr: string[] = [];
```

vs

```
let arr:Array<string> = [];
```

vs

```
let arr = [];
```

Webstorm doesn't seem to give errors if I push other stuff than strings tho.

Thoughts?

**Comment by wesleycho** [comment]
I personally like the second syntax for arrays, but not too opinionated here.

**Comment by pkozlowski-opensource** [comment]
My vote goes to `string[]` - short and doesn't look like Java ;-)

**Comment by Foxandxss** [comment]
Think of it like C# (which is what Typescript "stole" its idas).

The thing is, we will have to use generics more than probably, so the syntax will be back again :P
