### ISSUE TITLE
Convention: Split testing for behavior and UI

### ISSUE THREAD

**Issue by Foxandxss** [ng-bootstrap/core#75]
**Final Decision:** Follow the snippet on this message.

A component can be tested in two ways (and we should do both).

You can test the behavior like we used to test directive's controllers. No UI involved. For example testing that setting a new value on a progressbar, triggers the logic to calculate the new completion percentage.

You can also test UI, that involves the component creation. Same as testing directives as we used to in ui-bootstrap. Following the previous example. We can test that changing the value, the progressbar width changed with the new value.

For this, I propose:

```
describe('componentname', () => {
  // some common code / matchers / initialization

  describe('business logic', () => {
  });

  describe('UI', () => {
  });
});
```

**Comment by pkozlowski-opensource** [comment]
+1

Not sure about the `behavior` name yet, but nothing better comes to my mind right now.

**Comment by Foxandxss** [comment]
Yeah, naming is not that good tbh.

**Comment by wesleycho** [comment]
Business logic perhaps? This does sound good to me though, we should have better organization around tests.

**Comment by Foxandxss** [comment]
Yes, better.
