### ISSUE TITLE
Popover

### ISSUE THREAD

**Issue by BobbieBarker** [ng-bootstrap/core#9]
Recreate BS3 Popover with ng2 component.

**Comment by RobJacobs** [comment]
We're going to need a positioning service first.  May want to consider a service for managing the triggers rather than have that logic in the popover component.  May want to consider a distinct and separate component from the tooltip component as what is in the existing library is unwieldy.

**Comment by pkozlowski-opensource** [comment]
Blocked on https://github.com/angular/angular/issues/9293 and https://github.com/angular/angular/issues/8617
