### ISSUE TITLE
Question: Local Development and Bootstrap4

### ISSUE THREAD

**Issue by sirajc** [ng-bootstrap/core#93]
If one need to modify/add components, How to test them locally on browser to see whats happening on the UI and for interaction? Currently it's on tests.
We are not pulling bootstrap css locally, then how can we verify the widgets look and feel
Do you plan to support Bootstrap4 or Bootstrap3. Plunker examples are shown for bootstrap3 however issue #1 is being tracked for Bootstrap4

**Comment by Foxandxss** [comment]
So to see visually what are you doing, you have two options:

You can use a plunker (all plunkers in the README are bootstrap 4). Fork one of our plunker and you can play with them (I should update them to latest versions, that too).

There is a better option I use in every library project. Create a playground application inside the library that will be an application where you can load the library and play with it. You just add it to your global gitignore (if you don't have one, you can create one) and well, it is the best way to play with a library.

I personally use http://puu.sh/ljd03/b1868e9521.zip

Download that, extract the `playground` folder, copy it inside the root folder of this project, `npm install` and to run the server `npm run dev`.

Just require what you need in `app.ts` and use it.

And yes, everything is bootstrap 4.

**Comment by icfantv** [comment]
@sirajc, just a note that this project is in pure development mode and the code base is incredibly volatile.  I would not rely on anything here being even remotely stable for a while.

**Comment by sirajc** [comment]
@Foxandxss, Thanks for the details and Playground code, I was able to extend it and display all three components in one page.
One question, For rating we need glyphicons which are not part of Bootstrap 4, I used font-awesome locally, what are our goals which icons library are we planning to use?

@icfantv, Thanks for the note, I am not intending to use this as of now, in fact I am planning to do some contribution, so am just getting familiar with this ecosystem

**Comment by Foxandxss** [comment]
Bootstrap is not even final. When it reaches beta or RC, I will see what their decisions are with the icons and act accordingly.
