### ISSUE TITLE
Testing workflows

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#99]
I'm very much used to 2 testing workflows where I've got 2 separate commands (gulp or whatever):
* `gulp tdd` - do whatever compilation / preparation, start Karma in watch mode. Re-compile code /tests on each change and re-run Karma tests
* `gulp test` - do whatever compilation / preparation, start Karma in single-run mode and exit

After quick look at the current gulp file I don't see commands corresponding to those 2 workflows.

How do you guys work on tests? What is your workflow? Do we need to add / change anything in our build?

**Comment by Foxandxss** [comment]
I open two tabs:

`$ gulp watch`
`$ karma start`

That way I have watching mode.

then:

`$ gulp`

that before I commit to check that everything (including clang) is OK.

I will try if I can merge those two commands in one and create a PR.

**Comment by Foxandxss** [comment]
I see no way to merge both commands to create a `gulp tdd`. Karma watches, that for sure, but it needs to trigger transpilation too.

**Comment by pkozlowski-opensource** [comment]
> I see no way to merge both commands to create a gulp tdd

No worries, I can give it a shoot later this week

**Comment by Foxandxss** [comment]
It needs a preprocessor perhaps (there is one, but seems unmaintained a bit).

**Comment by Foxandxss** [comment]
I might add that I would love to get rid of chrome. It is a pain to need to have both the terminal and browser visible, or it would fail.
